// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYad6qzhCfMl4zeVmxe9MCyOwVoYOq21Q',
    appId: '1:151635480039:web:ee972bd6c06fc78bcdc142',
    messagingSenderId: '151635480039',
    projectId: 'red-cristiana-pigo',
    authDomain: 'red-cristiana-pigo.firebaseapp.com',
    storageBucket: 'red-cristiana-pigo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu342gzKR9A9FJ_PwcSxsGbflAjhD9ftI',
    appId: '1:151635480039:android:2e505d9981ed3cf1cdc142',
    messagingSenderId: '151635480039',
    projectId: 'red-cristiana-pigo',
    storageBucket: 'red-cristiana-pigo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzXKcyMiG-LkpcTaa13byZ2cnEMw90NSQ',
    appId: '1:151635480039:ios:9d6ba7c37ba5a0b3cdc142',
    messagingSenderId: '151635480039',
    projectId: 'red-cristiana-pigo',
    storageBucket: 'red-cristiana-pigo.firebasestorage.app',
    iosBundleId: 'com.example.redCristiana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzXKcyMiG-LkpcTaa13byZ2cnEMw90NSQ',
    appId: '1:151635480039:ios:9d6ba7c37ba5a0b3cdc142',
    messagingSenderId: '151635480039',
    projectId: 'red-cristiana-pigo',
    storageBucket: 'red-cristiana-pigo.firebasestorage.app',
    iosBundleId: 'com.example.redCristiana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYad6qzhCfMl4zeVmxe9MCyOwVoYOq21Q',
    appId: '1:151635480039:web:f95b106d2d703d62cdc142',
    messagingSenderId: '151635480039',
    projectId: 'red-cristiana-pigo',
    authDomain: 'red-cristiana-pigo.firebaseapp.com',
    storageBucket: 'red-cristiana-pigo.firebasestorage.app',
  );
}
